import { TIMING } from '~/constants';

export const DEFAULT_TERMINAL_TEXT_DURATION = TIMING.TERMINAL_TEXT_DEFAULT_DURATION;
export const DEFAULT_TERMINAL_TEXT_DELAY = TIMING.TERMINAL_TEXT_DEFAULT_DELAY;
