export const PASSWORD_LIST = [
  '123456',
  'password',
  '123456789',
  '12345',
  '12345678',
  'qwerty',
  '1234567',
  '111111',
  '123123',
  'iloveyou',
  'admin',
  '1234567890',
  'welcome',
  'secret',
  '123321',
  'password123',
  'monkey',
  'dragon',
  'nothing',
  'computer',
  'princess',
  'football',
  'letmein',
  'master',
  'sunny',
  'shadow',
  'sparkle',
  'jordan',
  'michael',
  'charlie',
  'superman',
  'pokemon',
  'blink-182',
  '555555',
  'freedom',
  'fuckyou',
  'trustno1',
  'liverpool',
  'arsenal',
] as const;

export const MAX_ROUNDS_STAYED = 2;

export const SARCASTIC_MESSAGES = [
  'even my dad has a better password_',
  'your password game is weaker than 123456_',
  'ACCESS DENIED... to good passwords_',
  'did you even try?_',
  'a script kiddie could do better_',
  'the matrix is disappointed_',
  'your firewall just cried_',
  'not even close, hacker wannabe_',
  'password security level: potato_',
  'brute force would be overkill here_',
] as const;

export type PasswordValue = (typeof PASSWORD_LIST)[number];
