export const TIMING = {
  TERMINAL_TEXT_DURATION: 1,
  TERMINAL_TEXT_DEFAULT_DURATION: 2,
  TERMINAL_TEXT_DEFAULT_DELAY: 0,
  REVEAL_DELAY: 2,
  ASCII_ART_DURATION: 1,
  GAME_START_SECONDS: 15,
  GAME_BONUS_SECONDS: 2,
} as const;
